"use client";

import { Clock3 } from "lucide-react";

export interface PromptVersion {
  id: number;
  title: string;
  type: "AI" | "USER";
  createdAt: string;
}

interface Props {
  versions: PromptVersion[];
  currentVersion: number;
  onSelect: (id: number) => void;
}

export default function VersionHistory({
  versions,
  currentVersion,
  onSelect,
}: Props) {
  return (
    <div className="mt-8 rounded-3xl border border-white/10 bg-[#0f172a] p-6">

      <h2 className="mb-5 text-xl font-semibold">

        Prompt History

      </h2>

      <div className="space-y-3">

        {versions.map((version) => (

          <button
            key={version.id}
            onClick={() => onSelect(version.id)}
            className={`w-full rounded-2xl border p-4 text-left transition ${
              currentVersion === version.id
                ? "border-blue-500 bg-blue-500/10"
                : "border-white/10 hover:border-blue-400"
            }`}
          >

            <div className="flex items-center justify-between">

              <div>

                <h3 className="font-semibold">

                  {version.title}

                </h3>

                <p className="mt-1 text-sm text-gray-400">

                  {version.type === "AI"
                    ? "Generated by AI"
                    : "Edited by User"}

                </p>

              </div>

              <div className="flex items-center gap-2 text-sm text-gray-500">

                <Clock3 size={15} />

                {version.createdAt}

              </div>

            </div>

          </button>

        ))}

      </div>

    </div>
  );
}