"""create prompt session tables

Revision ID: 58204f098d53
Revises: b7cbc0007c27
Create Date: 2026-07-03 20:08:03.277174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58204f098d53'
down_revision: Union[str, Sequence[str], None] = 'b7cbc0007c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_sessions_id'), 'prompt_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_sessions_session_uuid'), 'prompt_sessions', ['session_uuid'], unique=True)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('original_prompt', sa.Text(), nullable=True),
    sa.Column('enhanced_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['prompt_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_prompt_sessions_session_uuid'), table_name='prompt_sessions')
    op.drop_index(op.f('ix_prompt_sessions_id'), table_name='prompt_sessions')
    op.drop_table('prompt_sessions')
    # ### end Alembic commands ###
