"""create enhancement sessions

Revision ID: b7cbc0007c27
Revises: beb322b45933
Create Date: 2026-07-03 19:55:32.866424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cbc0007c27'
down_revision: Union[str, Sequence[str], None] = 'beb322b45933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhancement_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhancement_sessions_id'), 'enhancement_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_enhancement_sessions_session_id'), 'enhancement_sessions', ['session_id'], unique=True)
    op.drop_column('prompts', 'parent_id')
    op.drop_column('prompts', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('version', sa.INTEGER(), nullable=True))
    op.add_column('prompts', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_enhancement_sessions_session_id'), table_name='enhancement_sessions')
    op.drop_index(op.f('ix_enhancement_sessions_id'), table_name='enhancement_sessions')
    op.drop_table('enhancement_sessions')
    # ### end Alembic commands ###
